resources:
  - url: /local/monster-card.js
    type: js
name: Home
views:
  - title: Home
    cards:
      - type: vertical-stack
        cards:
        - type: entities
          title: Kitchen
          entities:
            - switch.on_air
            - light.kitchen
            - light.kitchen_table
            - light.kitchen_accent
            - switch.fountain
        - type: glance
          title: Kitchen Sensors
          entities:
            - sensor.fountain_fill
            - entity: sensor.kitchen_zw100_temperature
              name: Temp
            - entity: sensor.kitchen_zw100_relative_humidity
              name: Humidity
            - entity: sensor.kitchen_zw100_luminance
              name: Light
            - entity: binary_sensor.kitchen_zw100_sensor
              name: Motion
      - type: entities
        title: Den
        entities:
          - light.den
          - fan.den
          # - media_player.family_room_speaker
      - type: entities
        title: Front Room
        entities:
          - light.front_room
      - type: entities
        title: Office
        entities:
          - light.office
          - switch.office_tv
          - switch.scanner
          - switch.audio_mixer
      - type: entities
        title: Master Bedroom
        entities:
          - light.master_bedroom
          - fan.master_bedroom
          - input_boolean.in_bed
      - type: entities
        title: Lounge
        entities:
          - light.lounge
          - switch.lounge_fan
      - type: entities
        title: TJ's Room
        entities:
          - switch.tjs_desk_lamp
      - type: entities
        title: Laundry
        entities:
          - sensor.washer
          - sensor.dryer
      - type: entities
        title: Halls
        entities:
          - light.downstairs_hall
          - light.upstairs_hall
      - type: entities
        title: Garage
        entities:
          - cover.garage
          - sensor.garage
      - type: entities
        title: Outside
        entities:
          - switch.outside_back
          - lock.front_door_lock
          - sensor.front_door_status
      - type: weather-forecast
        title: Weather
        entity: weather.galloway
      - type: iframe
        url: https://embed.windy.com/embed2.html?overlay=radar
        aspect_ratio: 75%

      - type: custom:monster-card
        card:
          type: entities
          title: Stuff On
        filter:
          include:
            - domain: light
              state: 'on'
            - domain: switch
              state: 'on'
          exclude:
            - entity_id: "*undercounter*"
            - entity_id: light.hue_lightstrip_plus_1
            - entity_id: switch.outside_front
            - entity_id: switch.outside_lights
            - entity_id: switch.dryer_switch
            - entity_id: switch.washer_switch
            - entity_id: switch.scanner

  - tab_icon: mdi:cctv
    title: Cameras
    cards:
      - type: picture-entity
        entity: camera.driveway
      - type: picture-entity
        entity: camera.front_door
      - type: picture-entity
        entity: camera.stairs
      - type: picture-entity
        entity: camera.kitchen
      - type: picture-entity
        entity: camera.den
      - type: picture-entity
        entity: camera.office
      - type: picture-entity
        entity: camera.octoprint

  - tab_icon: mdi:auto-fix
    title: Automation
    cards:
      - type: custom:monster-card
        filter:
          include:
            - domain: automation
        card:
          title: Automations
          type: entities
      - type: custom:monster-card
        filter:
          include:
            - domain: script
        card:
          title: Scripts
          type: entities
