- alias: 'Fountain Motion Trigger'
  trigger:
    platform: state
    entity_id: binary_sensor.sensor
    to: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.fountain
    - service: timer.start
      entity_id: timer.fountain

- alias: 'Fountain Motion Reset'
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.fountain
  action:
    service: switch.turn_off
    entity_id: switch.fountain

