- alias: 'Kitchen Accent Motion Trigger'
  trigger:
    platform: state
    entity_id: binary_sensor.sensor
    to: 'on'
  condition:
    condition: numeric_state
    entity_id: sensor.kitchen_zw100_luminance
    below: 5
  action:
    - service: homeassistant.turn_on
      data:
        entity_id:
          - light.kitchen_accent
          - input_boolean.kitchen_accent_motion_triggered
    - service: timer.start
      entity_id: timer.kitchen_accent

- alias: 'Kitchen Accent Motion Reset'
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.kitchen_accent
  condition:
    condition: state
    entity_id: input_boolean.kitchen_accent_motion_triggered
    state: 'on'
  action:
    service: homeassistant.turn_off
    data:
      entity_id:
        - light.kitchen_accent
        - input_boolean.kitchen_accent_motion_triggered

