- alias: 'Stopped Printing'
  trigger:
    platform: state
    entity_id: sensor.octoprint_current_state
    from: 'Printing'
  action:
    - service: script.notify_tts
      data:
        message: OctoPrint stopped printing.
