- alias: TJ Bedtime
  trigger:
    platform: time
    at: '21:00:00'
  condition:
    - condition: time
      weekday:
        - sun
        - mon
        - tue
        - wed
        - thu
  action:
    - service: tts.google_say
      data:
        entity_id: media_player.family_room_speaker
        message: It is time for TJ to go to bed.
    - service: switch.turn_on
      entity_id: switch.on_air

- alias: TJ in Bed
  trigger:
    platform: time
    at: '21:10:00'
  condition:
    - condition: time
      weekday:
        - sun
        - mon
        - tue
        - wed
        - thu
  action:
    - service: switch.turn_off
      entity_id: switch.on_air

